/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // DronePilot Brand Colors
        primary: "#44f3a9",
        "primary-container": "#00d68f",
        "primary-fixed": "#54feb3",
        "primary-fixed-dim": "#27e199",
        secondary: "#b1c5ff",
        "secondary-container": "#006bfe",
        "secondary-fixed": "#dae2ff",
        "secondary-fixed-dim": "#b1c5ff",
        tertiary: "#ffcea9",
        "tertiary-container": "#ffa85e",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        background: "#0d1510",
        "on-background": "#dce5dc",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "on-primary": "#003822",
        "on-primary-container": "#005737",
        "on-primary-fixed": "#002112",
        "on-primary-fixed-variant": "#005234",
        "on-secondary": "#002c72",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed": "#001847",
        "on-secondary-fixed-variant": "#0040a0",
        "on-surface": "#dce5dc",
        "on-surface-variant": "#bacbbe",
        surface: "#0d1510",
        "surface-bright": "#333b35",
        "surface-container": "#19211c",
        "surface-container-high": "#242c26",
        "surface-container-highest": "#2e3731",
        "surface-container-low": "#151d18",
        "surface-container-lowest": "#08100b",
        "surface-dim": "#0d1510",
        "surface-tint": "#27e199",
        "surface-variant": "#2e3731",
        
        // Light / Alternate / Neumorphic Theme overrides
        alt: {
          background: "#eeebe3",
          surface: "#fcf9f7",
          "surface-container-lowest": "#ffffff",
          "surface-container-low": "#f6f3f1",
          "surface-container": "#f0edec",
          "surface-container-high": "#eae8e6",
          "surface-container-highest": "#e5e2e0",
          "on-surface-variant": "#444844",
          outline: "#747874",
          primary: "#000201",
          secondary: "#ca0013",
        }
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2.5rem",
        "full": "9999px"
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        base: "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "container-padding-desktop": "40px",
        "container-padding-mobile": "20px"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "Nunito Sans", "sans-serif"],
        body: ["DM Sans", "Nunito Sans", "sans-serif"],
      }
    },
  },
  plugins: [],
}
